name = "bk03/02-parametered_sc"
version = "0.0.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'bk03/02-parametered_sc'"

[repository]
user = "bk03"
project = "02-parametered_sc"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
